### PR TITLE
LPS-69599 & LPS-69449

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by blzaugg** [comment]
I guess LPS-69449 is not needed, as it's already in master.

**Comment by jonmak08** [comment]
ci:reopen

**Comment by jonmak08** [comment]
ci:retest

**Comment by blzaugg** [comment]
@jonmak08, anything I need to do with these failures?

**Comment by jonmak08** [comment]
Hey @blzaugg,

It does not seem like your changes caused these errors.  The CI test have been flagging a bunch of errors lately.

**Comment by jonmak08** [comment]
Reviewed. Thanks!
Pull request submitted at: https://github.com/jonmak08/liferay-portal/pull/1782

View just my changes: https://github.com/jonmak08/liferay-portal/compare/blzaugg:43b18de6a3...96521cec75
View total diff: https://github.com/jonmak08/liferay-portal/compare/f1ab7cbe22...96521cec75

**Comment by jonmak08** [comment]
Reviewed. Thanks!
Pull request submitted at: https://github.com/Preston-Crary/liferay-portal/pull/387

View just my changes: https://github.com/jonmak08/liferay-portal/compare/blzaugg:43b18de6a3...fddd6a33f6
View total diff: https://github.com/jonmak08/liferay-portal/compare/f1ab7cbe22...fddd6a33f6

**Pull request closed without merging**
