### PR TITLE
[TECHNICAL-SUPPORT] LPS-78807

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @fortunatomaldonado

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
See notes on https://github.com/gregory-bretall/liferay-portal/pull/43

**Comment by jonmak08** [comment]
Hey @jonathanmccann and @fortunatomaldonado,

I understand the purpose of the change, but one question I had was why the change from ```<%= randomNamespace %>``` to ```<portlet:namespace />```?  Shouldn't we convert all of the ```<%= randomNamespaces %>``` ```<portlet:namespaces />```?

Just wondering why some where changed and others were not.

**Comment by jonmak08** [comment]
Hey @fortunatomaldonado,

I would say to go and check since having some as ```randomNamespace``` and others as ```<portlet:namespace />``` is very confusing.  If you were trying to match the for attribute in the label with the id attribute in the element, if we explicitly set the id in the element to the ```randomNamespace``` and the for attribute in the label with the ```randomNamespace``` wouldn't we get the same results and make sure everything is accessible still?

Thanks!

**Comment by fortunatomaldonado** [comment]
Hello @jonmak08,

I apologize for the late response. I will go through and check the outcome of the changes when I have a chance. I am currently working on other high priority issues at the moment and may get to this in a few days. 

What I have noticed when using `randomNamespace`, the content would be `'Random-Letters'_null_null_'Portlet-Name'`. I am unsure of whether we want the id/for attribute to contain `null_null_`. Any insight in this is appreciated.

Thank you!

**Comment by fortunatomaldonado** [comment]
Hello @jonmak08, 

Looking further into the issue, the for attribute is determined by the name attribute aui:fieldwrapper and it will always contain `_com_liferay_users_admin_web_portlet_UsersAdminPortlet_` which is the `portlet:namespace />`.
We will need to keep `<portlet:namespace />` for the id attribute but we could also add the `randomNameSpace` to make sure all the attributes are unique. There is still the issue with having `null_null_` if we add `randomNameSpace` though.
Let me know what you think.

Thank you for the help !

**Comment by fortunatomaldonado** [comment]
Hello @jonmak08,

I agree, we should keep the `randomNameSpace` in order to keep each taglib unique.

I will open a new ticket for the `null_null` bug. Once that issue is resolved, I will continue working on the original issue. Let me know if there is anything else that you think should be considered. 

Thank you for all your help!

**Comment by fortunatomaldonado** [comment]
Hello @jonmak08,

I found that the `null_null_` issue is a separate issue and so I have been working on this current issue. I have made the correct changes and tested them and will be sending a new PR.

Thank you for your help!

**Comment by jonmak08** [comment]
Hey @fortunatomaldonado,

Do you have the JIRA ticket for the ```null_null``` error?  I just saw you sent an updated pull request for https://issues.liferay.com/browse/LPS-78807.

Please let me know if you have any questions. Thanks!

**Comment by fortunatomaldonado** [comment]
Hello @jonmak08,

Here is the ticket: https://issues.liferay.com/browse/LPS-79094
Let me know if anything else is needed.

Thanks!

**Pull request closed without merging**
