### PR TITLE
[TECHNICAL-SUPPORT] LPS-75855

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @gregory-bretall

### CODE REVIEW

**Comment by jonmak08** [comment]
Hey @jonathanmccann and @gregory-bretall,

I was not able to get this issue to reproduce correctly on master.  Are you sure this is an issue there?

**Comment by jonmak08** [comment]
These changes are without anything in this pull request.

Before deploying your theme in 70x, I get:
image

After deploying your theme, in 70x, I get:
image

Before deploying your theme in master, I get:
image

After deploying your theme in master, I get:
image

**Comment by gregory-bretall** [comment]
I'm having trouble testing this @jonmak08, I'll look into it more on Monday (I'm out tomorrow).

**Comment by gregory-bretall** [comment]
Hi @jonmak08,
I was finally able to retest this today. I tested it out on a cleanly deployed master, git hash 64ab8d69562bf506ec693d4d79523b4c2b3574b5, and was still seeing the same behavior before and after adding the theme I attached on the ticket. I'm honestly not sure what could be causing this discrepancy in results, do you have any ideas?

**Comment by jonmak08** [comment]
Reviewed. Thanks!
Pull request submitted at: https://github.com/shuyangzhou/liferay-portal/pull/5302
View total diff: https://github.com/jonmak08/liferay-portal/compare/0de4c6dd09...c5c5edf678

**Pull request closed without merging**
