### PR TITLE
[TECHNICAL-SUPPORT] LPS-77839

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @gregory-bretall

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey guys, I'm not sure this is a valid issue, specially for the backporting purposes. If I remember correctly, for 7.0, it was decided that navigation should only happen on the title section and not the image itself. 

For 7.1, we should verify the expected behaviour with UX.

**Comment by jonmak08** [comment]
Hey @jonathanmccann and @gregory-bretall,

Can you create a PTR ticket regarding this issue to see if it is a valid ticket and to see what the resolution should be?

If it is that the images should be clickable, I will create this.  If not, we can close this out and tell the customer.

Can you link the PTR tickets when you create them?

Please let me know if you have any questions. Thanks!

**Comment by gregory-bretall** [comment]
Hi @jonmak08,
I created a PTR for the issue https://issues.liferay.com/browse/PTR-259. Please let me know if I left anything out from the PTR.

**Comment by jonmak08** [comment]
Hey @gregory-bretall,

The PTR ticket looks good.  Let's just wait and hear what they have to say before proceeding with this ticket.

Thanks!

**Comment by jbalsas** [comment]
Hey guys, haven’t had time to go over it today... but you do realize you basically asked me through the PTR, right? 😂

I’m quite confident the current behaviour is the correct one for 7.0.x. At least the one we had to settle for at the time. I don’t think it’s prudent to change it now for our existing version.

What we can do is get clarification for master and future versions from the Lexicon team, just to make sure we don’t miss anything. You can check how the cards work in the clay site, which should honor the new requirements.

To clarify:
* This is working as expected for 7.0. No change should be made in the existing version
* For 7.1 (master), we need to compare with clay impl and ask UX

/cc @antonio-ortega

**Comment by gregory-bretall** [comment]
My question @jbalsas is if there's somewhere we can point to as a source for why this is seen as the correct behavior as it doesn't seem to be considering that the link attribute inside the card's div doesn't do anything under the current 7.0.x behavior.

**Comment by jbalsas** [comment]
For 7.0 that would be in the old designs and more likely in informal conversations we had while implementing it. 

There was quite some back and forth and what we have is what we settled for. Just disregard the implementation The behaviour is the one that was intended/agreed.

Moving forward, the lexicon site (lexicondesign.io) should contain that information. It is also collected in the internal documents that the UX team shares with us when working on the implementations.

**Comment by gregory-bretall** [comment]
As a further question then @jbalsas, why is the link still included if it is not meant to be clicked? I ask this because while I do not doubt that this is intentional behavior, the issue is being perceived as a bug by the customer and telling the customer that this is just the way we intended it without any further explanation will likely not be sufficient. 

What I would like to know then is, if you can't give any concrete reasoning behind the general implementation then an explanation as to exactly what purpose the link being there but not being clickable serves, because from my point of view all it is doing is confusing the intended behavior from an outside perspective.

**Comment by jbalsas** [comment]
Hey @gregory-bretall, that's an implementation detail, it really needs no further explanation. There are million ways we could've implemented that. There are better ways and worse ways, and that's just the one we have. 

Regarding confusing clickable links... we have plenty more of them throughout the portal that don't serve a navigation purpose:
- Links serve as togglers for dropdowns
- Links open dialogs (see permisions and other -> `_useDialog` attribute)
- Links serve as buttons to execute actions (search for `href="javascript:;` throughout the portal)

**Comment by jbalsas** [comment]
Just to double check... the bug says that if you click in an image in a card, that doesn't navigate to the url that for some reason you know it has

Visually, however, there is no visual indication that would lead you to think that's a link, so it is only confusing if you are ripping it open and assume how it should work based on your assumptions.

**Comment by gregory-bretall** [comment]
I believe the customer/CS's argument here largely stems from clickable tile icons being a common UX on many sites, but that really comes down to a semantic UX argument so I agree with your point of view here. @jonmak08 feel free to close this PR.

**Comment by jbalsas** [comment]
You're totally right, and that's totally understandable, @gregory-bretall. We had that same discussion over and over two years ago... should clicking on the tile select or navigate? It's not an easy choice, and you definitely can get behind any of them.

Google Drive and similar, for instance, go with the more desktop-like behaviour of 1-clik-to-select, double-click-to-enter. 

When faced with contextual selection like the one we have, where you want to select things and operate on them as well as navigate into them, the driving factor is how easy would it be to achieve both... leaving only the checkbox to select the entries might make that task daunting, and could lead to many missed-clicks that would navigate away of the admin panel.

I'm fine getting it to work one way or another, I don't think I have a strong preference, so behaviour-wise, I just trust our UX guys :)

**Pull request closed without merging**
