### PR TITLE
LPS-121928

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jonmak08,

Attached is an update for http://issues.liferay.com/browse/LPS-121928.

**Test Plan:**

1. Build Liferay Portal w/ DXP Modules
2. Login to Liferay
3. Click the **Applications Menu**
4. Go to **Applications** -> **Search Tuning** -> **Synonyms**
search-synonyms

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Review by julien — APPROVED** [review]

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/liferay-search/liferay-portal/pull/98

**Pull request closed without merging**
