### PR TITLE
LPS-55048

### PR DESCRIPTION
**Pull request by westonhancock**
Hey @jonmak08 

Here is an update for [LPS-55048](https://issues.liferay.com/browse/LPS-55048).
Let me know if you have any questions.

### CODE REVIEW

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/natecavanaugh/liferay-portal/pull/3199
View total diff: https://github.com/jonmak08/liferay-portal/compare/9515079c33...be75c5584d

**Comment by jonmak08** [comment]
Hey @westonhancock,

Can you send me a backport of this fix to ee-6.2.x as well?

Please let me know if you have any questions.  Thanks!

**Comment by westonhancock** [comment]
Yeah, no problem.

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!

**Pull request closed without merging**
