### PR TITLE
[TECHNICAL-SUPPORT] LPS-68845

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @NolanChan

### CODE REVIEW

**Comment by jonmak08** [comment]
Hey @jonathanmccann and @NolanChan,

I am trying to reproduce this issue and I cannot reproduce it.  What I see is whenever the date picker popup window is looses focus, and the control panel is opened, the date picker popup window is hidden.

bug

Thanks!

**Comment by NolanChan** [comment]
This is how I did it:

datepicker

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/44188
View total diff: https://github.com/jonmak08/liferay-portal/compare/187816eb8e...18faac981b

**Pull request closed without merging**
