### PR TITLE
Lps 61982 popover

### PR DESCRIPTION
**Pull request by tylerwonglr**
Hey Jon, here's my current progress on this ticket!  There is one more fix needed to be done!

### CODE REVIEW

**Comment by tylerwonglr** [comment]
Hey Jon, 

Please check the PR!  Not completely sure if the fix is the right solution!  I was able to target the arrow on the Popover through a CSS change.  Could not find another place in /portal or /plugins that was using the Popover in the way that we are using it here.

Thanks,
Tyler

**Comment by juliocamarero** [comment]
Hey guys, 

we have just changed this UI. It is now a dialog and not a popover anymore.

thanks!

**Comment by jonmak08** [comment]
Thanks for the update @juliocamarero!

**Comment by jonmak08** [comment]
Hey @tylerwonglr,

Based on @juliocamarero's comments, I will close this pull request since it is no longer an issue.

Please let me know if you have any questions. Thanks!

**Pull request closed without merging**
