### PR TITLE
LPS-59844 TypeError when installing Xuggler

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-59844](https://issues.liferay.com/browse/LPS-59844).<br><br>/cc @andrewbetts @jbalsas @carloslancha

### CODE REVIEW

**Comment by drewbrokke** [comment]
ci:retest

**Comment by jonmak08** [comment]
Hey @andrewbetts @jbalsas @carloslancha, @drewbrokke, and @pei-jung,

I will look at this tomorrow since the test's are still pending.  Hopefully they pass and I can get to it tomorrow morning.

Please let me know if you have any questions.  Thanks!

**Comment by drewbrokke** [comment]
Hey @jonmak08, the above `PortletPreferencesFactoryImplGetPreferencesIdsTest` failures are failing on many pulls right now, just FYI.

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!

**Pull request closed without merging**
