### PR TITLE
LPS-69400 changing folder name

### PR DESCRIPTION
**Pull request by marcellustavares**
hey @jonmak08, could you please help me to review @linolaoj 's pull?

It looks good to me but let me know if you have any question.

 cc @brunobasto

Thx

### CODE REVIEW

**Comment by jonmak08** [comment]
Hey @linolaoj and @marcellustavares,

I saw that we are also using the ```<liferay-ui:custom-attributes-available />``` taglib inside of ```/portal/modules/apps/web-experience/journal/journal-web/``` as well, but that was not migrated to the new taglib.  I know that module falls under @juliocamarero's team, but should we change that one as well?

If so, can you make that change as well and then deprecate the existing usage of this old taglib and document it with the new one in ```BREAKING_CHANGES.markdown```?

**Comment by linolaoj** [comment]
Hi @jonmak08 ,
according to https://github.com/liferay/com-liferay-journal/pull/60#issuecomment-263839268 we need to  publish the jar before update the journal-web. So I intent to deprecate the old taglib and make the journal changes later. Do you think this a good way to go?

**Comment by linolaoj** [comment]
ci:reopen

**Comment by jonmak08** [comment]
Hey @linolaoj,

Can you look into why the source formatter is failing on this pull?

**Comment by linolaoj** [comment]
It is failing because of one line on expando-custom-field-ui-taglib/src/main/resources/META-INF/resources/init.jsp. I don't know why the SourceFormatterTest didn't catch it before. Do you want me to resend?

**Comment by jonmak08** [comment]
You can just add a commit to this pull since it is still open.  I have not pulled it down yet, but as far as I can tell, everything looks good in this.

**Comment by linolaoj** [comment]
I send a new one https://github.com/jonmak08/liferay-portal/pull/1654, because this was on marcellus branch, so I could not add a commit.

Sorry for the trouble :)

**Comment by jonmak08** [comment]
Closing this pull request in favor of https://github.com/jonmak08/liferay-portal/pull/1654

**Pull request closed without merging**
