### PR TITLE
LPS-53806

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @dustinryerson

### CODE REVIEW

**Comment by jonmak08** [comment]
Hey @dustinryerson and @jonathanmccann,

With this change do we have to account for the duplicated MST in the select menu?

screen shot 2015-03-04 at 2 29 26 pm

Please let me know if you have any questions.  Thanks!

**Comment by dustinryerson** [comment]
Hey @jonmak08,

There are two Mountain Standard Time options because one is the default MST option and the other represents the Mountain Daylight Time option. The Mountain Daylight Time option only shows when Daylight Savings Time is active in the user's time zone, otherwise it will also show MST.

Please let me know if you have any other questions.

Thank you!

**Comment by jonmak08** [comment]
Hey @dustinryerson,

Do we need to change the label to be Mountain Daylight Time then?  It just seems weird to have 2 of the same options/labels.

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/natecavanaugh/liferay-portal/pull/3146
View total diff: https://github.com/jonmak08/liferay-portal/compare/f1f1b5a5f1...b2fc324ab6

**Comment by dustinryerson** [comment]
Here's the LPS regarding the two Mountain Standard Time options in the time zone selection drop down: https://issues.liferay.com/browse/LPS-53996

**Pull request closed without merging**
