### PR TITLE
[Technical Support] LPS-69112 Calendar portlet styling is broken when displayed in a layout column smaller than the full page

### PR DESCRIPTION
**Pull request by dustinryerson**
/cc @brandizzi

Hey @jonmak08,

This is an update for https://issues.liferay.com/browse/LPS-69112, and a resend for https://github.com/jonmak08/liferay-portal/pull/1630. I've fixed the cases you pointed out on my previous pull request. Does this solution cover all the concerns we discussed?

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by dustinryerson** [comment]
@jonmak08 one quick note, one of the things we discussed was having these changes be compatible with any possible changes to bootstrap in the future. I'm not sure if my changes do this fully, so if not please let me know.

**Comment by dustinryerson** [comment]
One more quick note: Opening the sidenav messes up the styling. I talked that issue over with Minhchau and we thought we'd have to use JavaScript to address that issue if it's one we'd actually want to fix. Let me know if you have any thoughts about this cases.

Thanks!

**Comment by dustinryerson** [comment]
ci:reopen

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/brandizzi/liferay-portal/pull/340

View just my changes: https://github.com/jonmak08/liferay-portal/compare/dustinryerson:f7584342e6...a45c0b7690
View total diff: https://github.com/jonmak08/liferay-portal/compare/00b3ef7cf1...a45c0b7690

**Pull request closed without merging**
