### PR TITLE
LPS-86456

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by blzaugg** [comment]
@jonmak08 I've not publish any Maven stuff. I assume I can't. Can you show me this on Monday?

**Comment by jbalsas** [comment]
Hey @blzaugg, in Liferay Portal, AlloyEditor uses the patched CKEditor rather than a standalone instance of CKEditor. See https://github.com/liferay/liferay-portal/blob/master/modules/apps/frontend-editor/frontend-editor-alloyeditor-web/src/main/resources/META-INF/resources/resources.jsp#L36

**Comment by jonmak08** [comment]
Reviewed. Thanks!
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/65145
View total diff: https://github.com/jonmak08/liferay-portal/compare/f4b6b3ae81...2360ce5071

**Pull request closed without merging**
