### PR TITLE
LPS-53769 - Content saved using TinyMCE does not save the formatting of content

### PR DESCRIPTION
**Pull request by mjbradford89**
Hi Jon,

Attached is an update for https://issues.liferay.com/browse/LPS-53769.

This one was caused by ba3676b in https://issues.liferay.com/browse/LPS-53162. I don't think the ```getBody().textContent``` change was intended for tinymce, only tinymce_simple.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/natecavanaugh/liferay-portal/pull/3132

View just my changes: https://github.com/jonmak08/liferay-portal/compare/mjbradford89:0f465ec9dd...41f65bc673
View total diff: https://github.com/jonmak08/liferay-portal/compare/b2602b47d2...41f65bc673

**Comment by jonmak08** [comment]
Hey @mjbradford89,

With this change, we are now saving the entire contents of the iframe which now gets displayed when we output the contents in the view.jsp.  Should we be escaping the contents to only show text or should we be trying to save just the wrapping markup that we need?

blogs

Can you take a look at this and resend me a new pull if needed?

Please let me know if you have any questions.  Thanks!

**Comment by mjbradford89** [comment]
Hey @jonmak08 

Hmm that's strange.  I would say that tinymce shouldn't be used for the text-only fields like the title and subtitle in blogs.  We used to have separate portal properties for those fields, but it looks like that was removed in this commit 95d9a626e6e505f71ac17ac1a3835a7632f2cab1.  

I'll see if I can get the formatting to be saved for the blog content but not for the other fields.

**Comment by mjbradford89** [comment]
Hey @ambrinchaudhary 

Jon and I were wondering the purpose of the removal of the html vs text blogs portal properties in this commit 95d9a626e6e505f71ac17ac1a3835a7632f2cab1.  It's causing some issues if TinyMCE is used in blogs instead of AlloyEditor.  Was that change necessary for LPS-52975?

**Comment by ambrinchaudhary** [comment]
Hi @mjbradford89 

we did this change because when we included AlloyEditor in Comments, we needed to create another "property" different that "text" and "html" (it was in "text" mode, but we wanted some "html" mode with very few funcionalities). Also thinking that in other portlets we may want different configurations, we though the best way was to pass AlloyEditor his own configuration instead of creating several "modes" for AlloyEditor. That is why we removed "text" and "html" modes.

But I cannot see how this affects to TinyMCE...?? This should only affect AlloyEditor, as TinyMCE.jsp is not listening the "editorConfig" attribute...

Let me know if I can help you.

cc/ @ipeychev

**Comment by mjbradford89** [comment]
Thanks for clearing that up @ambrinchaudhary.

It doesn't directly effect TinyMCE.  We ran into an issue when we changed the new ```editor.wysiwyg.portal-web.docroot.html.portlet.blogs.edit_entry.jsp``` portal property to tinymce.  Which, since it does not support the editorConfig attribute, resulted in TinyMCE being used for the title, subtitle, and content fields in blogs. Which when saved, causes HTML to be saved in fields that should only support text.

In the past this was avoided with the two separate portal properties for html vs text, but now there isn't a way to set one without setting the other.

Do you know if it is planned to eventually support the editorConfig attribute in tinymce/ckeditor as well?

**Comment by ambrinchaudhary** [comment]
Hey @mjbradford89,
right now there is not plan to support editorConfig attribute in tinymce/ckeditor. I have been talking to @sergiogonzalez and PM if we should support other editors in Blogs, as we have added a lot of funcionality in AlloyEditor, which now has the best UX, and it is not clear if we should put effort in applying that changes in other editors. PM's are going to discuss it. Until then, please try to test TinyMCE in other portlets instead of Blogs.

**Comment by mjbradford89** [comment]
Sounds good. Thanks for the help!

**Pull request closed without merging**
