### PR TITLE
LPS-58388 Organizations and User Groups search results leave 'empty results' message after selecting

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-58388](https://issues.liferay.com/browse/LPS-58388).<br><br>/cc @pei-jung

### CODE REVIEW

**Comment by jonmak08** [comment]
Hey @drewbrokke,

For this issue, I don't like how we just remove the alert message entirely.  Can we update the ```selectEntity``` method to remove the alert in the opening window or is there a way to just repaint that div section when we close the window?

**Comment by drewbrokke** [comment]
Possibly, though it's a little specious that they're there in the first place.  They were not there before the OSGi migration; Pei-Jung put them in.  We both agreed that they didn't need to be added.

That being said, if you feel like it's an improvement to have the messages there, then we can look at re-rendering that section.  Do we have a standard way of re-painting besides using an ajax call?

**Comment by jonmak08** [comment]
Hey @drewbrokke,

I'm wondering if we can look at using ```liferay-surface``` and SPA for the repaint.  My only question is if someone turns off SPA in their ```portal.properties```, then how do we remove this alert?

**Comment by jonmak08** [comment]
Hey @drewbrokke,

I am closing this pull request so you can see if we can update this a different way like we mentioned.

Please let me know if you have any questions.  Thanks!

**Pull request closed without merging**
