### PR TITLE
LPS-83866 Setting the right fieldId from blogs

### PR DESCRIPTION
**Pull request by 4lejandrito**

### CODE REVIEW

**Comment by 4lejandrito** [comment]
Hi @jonmak08,

There was a small problem with your changes. There is a bit of logic in [blogs.js](https://github.com/liferay/liferay-portal/blob/38976a0a0512365c450df7eb515da14652213f23/modules/apps/blogs/blogs-web/src/main/resources/META-INF/resources/blogs/js/blogs.js#L330) that toggles the `disabled` css class when the radio button changes. With your changes the label's `for` attribute was no longer equal the input's `id` attribute. 

For this I added an extra field to the wrapper in which we explicitly specify the `id`of the input.

However by the time I sent you this pull request I realised that the same might have been achieved by changing the name [here](https://github.com/jonmak08/liferay-portal/pull/1937/commits/b22f5eb32dd91deeade010148c130a94380d7895#diff-4d0c5ffabc7d2c9b7b553c3debb791b7R277) to the input's name (urlTitle instead of urlTitleWrapper)  which is at the end set as the id.

I still think is more clear to explicitly specify the 'id' instead of rely on obscure logic that transforms names into ids.

I leave up to you to remove my 3 last commits and perform the change I mention in the name.

In both cases you can send directly to Brian.

Regards

**Comment by jonmak08** [comment]
Thanks @4lejandrito!  I will review and send directly to @brianchandotcom when the review is complete.

Please let me know if you have any questions. Thanks!  Appreciate your feedback!

**Comment by jonmak08** [comment]
Reviewed. Thanks!
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/61832

View just my changes: https://github.com/jonmak08/liferay-portal/compare/4lejandrito:8be6fd856d...d480f68205
View total diff: https://github.com/jonmak08/liferay-portal/compare/d038a22264...d480f68205

**Comment by jonmak08** [comment]
Hey @4lejandrito,

I went with removing those last 3 commits, to keep things consistent with all the other taglibs and how we link the input fields via the name.  I agree that it would be more clear if we added the ```fieldId``` attribute, but for consistency and since we are probably going to remove and deprecate these taglibs eventually, we will minimize the amount of change to the taglibs.

Please let me know if you have any questions. Thanks!

**Pull request closed without merging**
