### PR TITLE
Lps 105745 katie

### PR DESCRIPTION
**Pull request by SamZiemer**
Notes from @Katienesterovich:

> https://issues.liferay.com/browse/LPS-105745
> 
> Generated Theme
> image
> 
> Default Theme
> image
> 
> Changed the btn.secondary color to white - matching the atlas theme.
> Can't change the text color - will affect default theme.

### CODE REVIEW

**Comment by SamZiemer** [comment]
ci:test:sf

**Comment by SamZiemer** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
Reviewed. Thanks!
Pull request submitted at: https://github.com/pavel-savinov/liferay-portal/pull/471

View just my changes: https://github.com/jonmak08/liferay-portal/compare/SamZiemer:ad15470e2d...57d789075c
View total diff: https://github.com/jonmak08/liferay-portal/compare/634eeea1c7...57d789075c

**Comment by jonmak08** [comment]
Reviewed. Thanks!

**Pull request closed without merging**
