### PR TITLE
LPS-121898

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jonmak08,

Attached is an update for http://issues.liferay.com/browse/LPS-121898.

**Test Plan:**
1. Login to Liferay
2. Click on the **Applications Menu**
3. Click on **Control Panel** -> **Security** -> **Service Access Policy**
4. Click the `+` to add a new policy
service-access-policy

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Review by julien — APPROVED** [review]

**Review by ambrinchaudhary — APPROVED** [review]

**Review by markocikos — APPROVED** [review]
@jonmak08 Looks good, but probably not the right product team for the module :slightly_smiling_face:

**Comment by jonmak08** [comment]
ci:forward

**Pull request closed without merging**
