### PR TITLE
LPS-59844 TypeError when installing Xuggler

### PR DESCRIPTION
**Pull request by drewbrokke**
This is an update for [LPS-59844](https://issues.liferay.com/browse/LPS-59844).<br><br>/cc @arbetts @pei-jung @jorgeferrer

### CODE REVIEW

**Comment by jbalsas** [comment]
Hey guys!

We ran into this same issue as part of another story a few hours ago and tried to find a solution for it before we realized it had already been reported.

@carloslancha came up with this [simpler fix](https://github.com/jbalsas/liferay-portal/pull/251) that only requires js changes to work. It also avoids moving js back to jsps which we definitely don't want :wink: 

We're wondering if all the work done here was meant for something else than just fixing the bug. If that's the case, maybe we could fix this using @carloslancha suggestion and then rework the extra portlet logic on top of that. We can send you guys a PR to verify this.

What do you think?

**Comment by jonmak08** [comment]
Hey @drewbrokke, @arbetts, @pei-jung, and @jorgeferrer,

Can you take a look at @jbalsas's comments and provide your input and suggestions?

Please let me know if you have any questions.  Thanks!

**Comment by arbetts** [comment]
there are probably a few reasons, but one of the major ones for me is that we were using the progressTag in only this instance, and the progress tag was not really providing much value.

it only had two stages 15% and 75% and we never actually transitioned to the 75% in the code. so the user would see 0 15 100, which is not much of a progress bar. so these changes were in part to deprecate the progressTag.

as far as code being in the jsp... we can easily transfer the one aui:script block into main.js instead of having it in the jsp.

maybe @drewbrokke can explain some more

**Comment by jbalsas** [comment]
Hey @arbetts, I'm all for deprecating the `progressTag` taglib if it's not really necessary.

Just mention that it looks here that we are removing the `cmd` from the form and doing a lot of other `Action-wise` changes that might be unnecessary based on @carloslancha fix.

Anyway, we just saw this and thought it could help simplifying the fix. We'll be happy if it gets fixed and we keep the jsps as clean from js code as possible.

**Comment by jbalsas** [comment]
Hey guys, any update on this? We have several blocked stories depending on the possibility to install Xuggler.

Any chance to get this over to Brian soon?

Thanks!

**Comment by drewbrokke** [comment]
Hey @jbalsas, I also like the idea of keeping the javascript out of the JSPs as much as possible.  I'd be fine putting our changes on top of @carloslancha's work, as we still want to end up deprecating the progressTag.

**Comment by drewbrokke** [comment]
We'll try to get this pushed through today if possible.

**Comment by arbetts** [comment]
i've run out of time today, but i'm almost ready to send the pull based on @carloslancha changes.

i'll be able to send it first thing on monday

**Comment by jbalsas** [comment]
Sounds great, guys, thanks a lot!

**Comment by jonmak08** [comment]
Hey @arbetts,

Let me know when you have everything updated and I will review this pull.

Please let me know if you have any questions.  Thanks!

**Comment by arbetts** [comment]
new pull sent to @drewbrokke 

https://github.com/drewbrokke/liferay-portal/pull/128

**Comment by jonmak08** [comment]
Closing pull request in favor of https://github.com/drewbrokke/liferay-portal/pull/128.

**Pull request closed without merging**
