### PR TITLE
LPS-70823 - Normalize Lexicon Sticker component in taglibs

### PR DESCRIPTION
**Pull request by pat270**
https://issues.liferay.com/browse/LPS-70823

### CODE REVIEW

**Comment by pat270** [comment]
ci:stop

**Comment by pat270** [comment]
ci:restart

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/47095
View total diff: https://github.com/jonmak08/liferay-portal/compare/e9680db0a2...1ae588271e

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/47098
View total diff: https://github.com/jonmak08/liferay-portal/compare/e9680db0a2...bbabf664ef

**Pull request closed without merging**
