### PR TITLE
LPS-65089 - Fix layout tree from nesting containers when deleting from product menu

### PR DESCRIPTION
**Pull request by thektan**
Udpate for: https://issues.liferay.com/browse/LPS-65089

### CODE REVIEW

**Comment by jonmak08** [comment]
Hey @thektan,

When I test with this fix, I get another JS error ```Uncaught TypeError: Cannot read property 'plug' of null``` when deleting the pages.  Can you take a look at this?

**Comment by thektan** [comment]
@jonmak08 Hmm, that's strange. I just tested it on Chrome and Firefox and I don't seem to be getting any errors. Seems like it might have to do with the `<portlet:namespace/>` not matching up, causing the container to not be found (https://github.com/jonmak08/liferay-portal/pull/1553/commits/3635dbceed23346c7c699d63f232a11cfc036282#diff-c21882b324b223d67a70526440cd8a04R324) since after the ajax call, the portlet:namespace is different. But I don't think it should be an issue since the entire container is being replaced with the new namespace too.

If you get around to testing this again, let me know if you're still getting the error since I don't seem to be able to reproduce it.

Thanks!

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/juliocamarero/liferay-portal/pull/4125
View total diff: https://github.com/jonmak08/liferay-portal/compare/9ce0739dce...dcba32564b

**Comment by jonmak08** [comment]
I think it was cache causing the issues.  I deleted everything and rebuilt today and no errors.

**Pull request closed without merging**
