### PR TITLE
LPS-66236 Vertical images should always have left 0

### PR DESCRIPTION
**Pull request by marcoscv-work**

### CODE REVIEW

**Comment by marcoscv-work** [comment]
Hey @jonmak08 , we are not sure about if this is the correct solution, I mean the problem comes from 'crop AUI component', and @ambrinchaudhary fixed it by using a not so esthetic !important to overwrite by CSS what sometimes the AUI component provides wrong.

What do you think?

**Comment by sergiogonzalez** [comment]
Hey @jonmak08 can you please review this pull when you have some time?
Thanks!

**Comment by jonmak08** [comment]
Hey @sergiogonzalez,

Yes, I will get to this tomorrow.  I am trying to take care of a support issue, which I just finished.

**Comment by sergiogonzalez** [comment]
Thanks @jonmak08 👍

**Comment by jonmak08** [comment]
Reviewed. Thanks!
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/51157
View total diff: https://github.com/jonmak08/liferay-portal/compare/6d9834f675...ad593ce49b

**Pull request closed without merging**
