### PR TITLE
LPS-129479

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jonmak08,

Attached is an update for http://issues.liferay.com/browse/LPS-129479.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:forward

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
ci:forward

**Comment by brianchandotcom** [comment]
@jonmak08 I just merged this manually.

@pyoo47 not sure what was going on with CI.

**Comment by jonmak08** [comment]
Thanks @brianchandotcom!

**Pull request closed without merging**
