### PR TITLE
LPS-66646

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by jonmak08** [comment]
Hey @zxdgoal,

I think we need to revisit this fix for a few reason.  We have a ```selectEntity`` method (https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/util.js#L1527) which does something very similar to what you are trying to achieve in this fix.

@blzaugg had originally created a fix similar to this with https://github.com/liferay/liferay-portal/commit/c67b7cfae87c0596e36c360df26f3b2916075604.

What his fix does is leverage the ```Liferay.Util.selectEntity``` method for controlling which options are disabled in the dialog modal window that appears.  It uses a ```selectedData``` property which contains an array of the items selected to control the state of the buttons (https://github.com/liferay/liferay-portal/blob/master/modules/apps/foundation/frontend-js/frontend-js-web/src/main/resources/META-INF/resources/liferay/util.js#L1547...L1570).

I think your fix will need to add this ```selectedData``` property to all instances where ```Liferay.Util.selectEntity()``` is used.

One thing to do before doing any of this is standardizing the data attributes on the select buttons across the portal so we can look for the same data attribute in the JS.

I will send you a pull of a prototype of what I am talking about.

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/zxdgoal/liferay-portal/pull/15

**Comment by jonmak08** [comment]
We can also probably close https://issues.liferay.com/browse/LPS-66646 in favor of https://issues.liferay.com/browse/LPS-52814 and use https://issues.liferay.com/browse/LPS-52814 to backport the changes to ee-6.2.x as well.

Please let me know if you have any questions. Thanks!

**Comment by zxdgoal** [comment]
Thank you, Jon.

I see Byran's way should address my issue.

But did you mean to use ``Liferay.Util.selectEntity()`` instead where we have problem with `` selectEntityHandler``, or change `` selectEntityHandler`` to accept ``selectedData`` ?

John.

**Comment by jonmak08** [comment]
Hey @zxdgoal,

Everywhere we use ```selectEntityHandler```, there is an another JSP which calls ```selectEntity``` which opens the modal containing ```selectEntityHandler```.  I think we should be able to pass ```selectedData``` to the JSP calling ```selectEntity``` and that should resolve which items are selectable and disabled in the modal.

Please let me know if you have any questions. Thanks!

**Pull request closed without merging**
