### PR TITLE
LPS-69400 deprecate old taglib

### PR DESCRIPTION
**Pull request by linolaoj**

### CODE REVIEW

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by linolaoj** [comment]
ci:retest

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/45536

View just my changes: https://github.com/jonmak08/liferay-portal/compare/linolaoj:13c183cb85...567924986f
View total diff: https://github.com/jonmak08/liferay-portal/compare/1eeda37ce0...567924986f

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal/pull/45750 

New Pull Request: https://github.com/brianchandotcom/liferay-portal-ee/pull/15542

**Pull request closed without merging**
