### PR TITLE
LPS-77877 input-group-btn margin adjusted to include blue border of s…

### PR DESCRIPTION
**Pull request by ckorbel**
…earch bar

### CODE REVIEW

**Comment by jonmak08** [comment]
Closing since this is the wrong fix.  If we updated the Clay CSS ```z-index``` value to ```0```,  for ```.input-group-btn``` then the border will show up correctly.  We need to ask @pat270 if that is the correct fix for this or not.

Please let me know if you have any questions. Thanks!

**Comment by ckorbel** [comment]
Okay, I figured this would be a better fix, but I just need to track down
where this lives.

Is it safe to assume it's at least somewhere within:
modules/apps/foundation/frontend-css/ ?

**Comment by pat270** [comment]
@ckorbel remove `z-index: 1;` from `.input-group-btn` and add it to `.input-group-input`.

https://github.com/liferay/liferay-portal/blame/master/modules/apps/foundation/frontend-theme/frontend-theme-styled/src/main/resources/META-INF/resources/_styled/css/compat/components/_forms.scss#L198

**Comment by ckorbel** [comment]
thanks @pat270 when I remove  z-index: 1; from .input-group-btn  the border
shows up, but when I add it to any  .input-group-input it would comes back.

I tried to create a .input-group-input {z-index: 1} in a few places,but
that just threw everything off. Is it enough to just remove the z-index for
.input-group-btn?

**Comment by pat270** [comment]
@ckorbel if the focus border shows up on the right if you do that it's fine? I couldn't get it to show unless I added a z-index to `.input-group-input`.

**Comment by ckorbel** [comment]
Hmmm yeah I'm not sure what the difference is but for me the focus border
shows up on the right by just removing  z-index: 1; from .input-group-btn

**Pull request closed without merging**
