### PR TITLE
LPS-65608 Regen system.packages.extra.mf

### PR DESCRIPTION
**Pull request by brunobasto**

### CODE REVIEW

**Comment by jonmak08** [comment]
Hey @brunobasto and @inacionery,

Even with this fix, I still get the 414 error on liferay/master.  Can you guys recheck this solution or am I missing something?

**Comment by inacionery** [comment]
Hi @jonmak08,

The solution was to add the forcePost attribute in the taglib, but the default is false. So, you must set to true in SearchContainer.

**Comment by jonmak08** [comment]
Hey @inacionery,

Got it.  Should we change it to use the forcePost or only in certain cases?

**Comment by brunobasto** [comment]
Hey @jonmak08, I think the issue is that @inacionery discovered an issue with customer code and needed to make this forcePost available in the API although we don't have any portlets that have advanced searches that can have so much data that a GET request wouldn't be enough.

**Comment by jonmak08** [comment]
OK.  Thanks guys!

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!

**Pull request closed without merging**
