### PR TITLE
LPS-61804 Migrate ui:asset-metadata to asset-taglib module

### PR DESCRIPTION
**Pull request by thektan**
Hi Jon!

Attached is an update for https://issues.liferay.com/browse/LPS-61804. I moved the taglib to the `asset-taglib` module rather than copying it over.

Let me know if there are any issues. Thanks!

### CODE REVIEW

**Comment by thektan** [comment]
ci:retest

**Comment by thektan** [comment]
ci:retest

**Comment by thektan** [comment]
ci:retest

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/jbalsas/liferay-portal/pull/382

View just my changes: https://github.com/jonmak08/liferay-portal/compare/thektan:35cd1d2cf9...ae0f12ede8
View total diff: https://github.com/jonmak08/liferay-portal/compare/e91811ebf7...ae0f12ede8

**Pull request closed without merging**
