### PR TITLE
[TECHNICAL-SUPPORT] LPS-64945

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @dustinryerson

### CODE REVIEW

**Comment by dustinryerson** [comment]
cc @brandizzi

**Comment by jonmak08** [comment]
Hey @dustinryerson,

Do we know why this is not working?  Is this a Senna/SPA bug?

**Comment by jonmak08** [comment]
It might be an IE issue...

http://stackoverflow.com/questions/11210552/ie-loses-focus-on-input-field-in-modal

https://bugs.jquery.com/ticket/12319

**Comment by dustinryerson** [comment]
It was difficult for me to determine the exact cause of this issue. I also believe that it is likely an IE issue based on many resources I read similar to the articles you linked in your comment. For example, when I was debugging the issue I noticed that the following logic in the ```addInputFocus``` function in ```util.js``` was not run in IE as it was when using other browsers:  ```A.on('focus', handleFocus, document);``` and ```A.on('blur', handleFocus, document);```. This doesn't necessarily mean that this is the specific cause of the issue, but rather it led me to believe that IE is functioning differently than other browsers when it comes to focusing on iFrame elements.

**Comment by dustinryerson** [comment]
Should I look into the possibility that this is a Senna/SPA bug? Is there additional specific investigation / testing that you'd like me to perform for this issue?

**Comment by jonmak08** [comment]
Still investigating.  Need to see why the focusFormField does not actually work, but the code gets run.

**Comment by dustinryerson** [comment]
Based on my investigation and debugging, I think it's the other way around. The focusFormField function seems to work right, but it doesn't get run when using IE.

**Comment by jonmak08** [comment]
I just spoke with @dustinryerson and we are going to revisit this issues since it looks like there are quite a few issues with the ```focus()``` method in Javascript.  I suggested that he create a SDH for the client using a different approach.

1) Edit ```/portal/modules/apps/forms-and-workflow/calendar/calendar-web/src/main/resources/META-INF/resources/edit_calendar_booking.jsp``` by adding the ```autoFocus``` attribute to the ```<aui:input />``` on https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/calendar/calendar-web/src/main/resources/META-INF/resources/edit_calendar_booking.jsp#L234.

2) Remove https://github.com/liferay/liferay-portal/blob/master/modules/apps/forms-and-workflow/calendar/calendar-web/src/main/resources/META-INF/resources/edit_calendar_booking.jsp#L462 since the ```autoFocus``` attribute will now focus the element.

I would like to have someone test out why the ```Liferay.Util.focusFormField()``` is not working in all circumstances and/or browsers.  It might be due to the bugginess of the ```focus()``` method itself, but I just wanted to confirm that.

Please let me know if you have any questions. Thanks!

**Pull request closed without merging**
