### PR TITLE
[TECHNICAL-SUPPORT] LPS-85326

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @gregory-bretall

### CODE REVIEW

**Comment by jonathanmccann** [comment]
Tests passed here - https://github.com/jonathanmccann/liferay-portal/pull/1689

**Comment by jonmak08** [comment]
Hey @gregory-bretall and @jonathanmccann,

Shouldn't we just make the change to our version of CKEditor?  (See https://github.com/liferay/liferay-ckeditor/blob/ee-4.6.x/core/selection.js).  I think we should be making the change you added at https://github.com/liferay/liferay-ckeditor/blob/ee-4.6.x/core/selection.js#L1914.

Can you make the necessary change and resend?

Please let me know if you have any questions. Thanks!

**Comment by gregory-bretall** [comment]
The main reason I didn't change it there is because from what I can tell we've never made any changes to that repo since we branched it from normal CKEditor. If you really think that's the right path though @jonmak08 I have made the changes and sent them in at https://github.com/jonmak08/liferay-ckeditor/pull/7

**Comment by jonmak08** [comment]
Hey @gregory-bretall,

In the past, we have only committed actual merged fixes from CKEditor into that repository, but we maintain our own repository for the exact reason that you mention, when fixes do not get backported or merged to a specific branch in CKEditor, we can manage and maintain it ourselves.

Adding @blzaugg since he had helped maintain CKEditor for support previously.

**Comment by blzaugg** [comment]
Jon's right. We should be making the change in our CK repo, not making the change in Portal.

Currently, the `_diffs` folder is for adding plugins and configs, but not for patching anymore. I'm not sure patching was ever done in `_diffs`, it was done in `build.xml` and it was a mess. That's why our CK repo came about.

**Comment by blzaugg** [comment]
Here's an example of a customization/fix we did for CK.
https://github.com/liferay/liferay-ckeditor/commit/1ca098861e1bacc4672a7b54f170f876a6d7de0e

**Pull request closed without merging**
