### PR TITLE
LPS-87348

### PR DESCRIPTION
**Pull request by brianikim**
Resending from https://github.com/jonmak08/liferay-portal/pull/2003.

Only diff is buildLang as separate commit as requested in https://github.com/jonmak08/liferay-portal/pull/2003#issuecomment-449547280.

/cc @blzaugg

### CODE REVIEW

**Comment by brianikim** [comment]
ci:test:relevant

**Comment by brianikim** [comment]
This still needs to be reviewed when you are available @jonmak08

**Comment by jonmak08** [comment]
Reviewed. Thanks!
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/66355

View just my changes: https://github.com/jonmak08/liferay-portal/compare/brianikim:745f34032f...18a8ceb20d
View total diff: https://github.com/jonmak08/liferay-portal/compare/a5ee9541c6...18a8ceb20d

**Comment by jonmak08** [comment]
Reviewed. Thanks!

**Pull request closed without merging**
