### PR TITLE
LRDOCS-1375

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by blzaugg** [comment]
Seams fine.

**Comment by blzaugg** [comment]
ci:stop

**Comment by mwilliams2014** [comment]
@blzaugg @jonmak08 What else do we need to do to get this in?

**Comment by jonmak08** [comment]
Hey @mwilliams2014.

I can push this in.  I am not sure why it was closed, but I will keep you updated on its status.

Please let me know if you have any questions. Thanks!

**Comment by mwilliams2014** [comment]
Thanks @jonmak08 !

**Comment by jonmak08** [comment]
Reviewed. Thanks!
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/53700

View just my changes: https://github.com/jonmak08/liferay-portal/compare/blzaugg:e5ccf69ff3...7156d75c40
View total diff: https://github.com/jonmak08/liferay-portal/compare/72704826c9...7156d75c40

**Pull request closed without merging**
