### PR TITLE
LPS-62559 Fix navigation drag handles styles

### PR DESCRIPTION
**Pull request by thektan**
Hi @jonmak08,

Update for: https://issues.liferay.com/browse/LPS-62559

The drag handles seemed to only be appearing after directly interacting with the navigation menu on mobile which seemed off, so for mobile I instead fired the `initNavigation` event when the navigation bar is expanded. I had to use jQuery for the `shown.bs.collapse` event. If the current state of it is preferred, feel free to revert the commit.

Let me know if there are any issues. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/natecavanaugh/liferay-portal/pull/3824

View just my changes: https://github.com/jonmak08/liferay-portal/compare/thektan:52f5a205da...4cf66a2849
View total diff: https://github.com/jonmak08/liferay-portal/compare/f0841c4561...4cf66a2849

**Comment by jonmak08** [comment]
Hey @thektan,

I removed the commit https://github.com/thektan/liferay-portal/commit/48429d816768165a3d7f2029773302ac4824846b because it did not really relate to the ticket itself.  I will go ahead and create a new ticket for this issue and commit your fix against it.

Please let me know if you have any questions. Thanks!

**Comment by thektan** [comment]
Thanks @jonmak08!

**Comment by jonmak08** [comment]
New issue: https://issues.liferay.com/browse/LPS-63171

**Pull request closed without merging**
