### PR TITLE
LPS-55606

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @jgok

### CODE REVIEW

**Comment by jonmak08** [comment]
Hey @jgok,

I am trying to reproduce this issue on ee-6.2.x but am not able to reproduce the issue as described.  Can you please explain or provide a screencast of the issue?

Please let me know if you have any questions.  Thanks!

**Comment by jgok** [comment]
Do you have the latest SO installed? I had to have SO installed to reproduce this issue.

**Comment by jonmak08** [comment]
Hey @jgok,

Yes, I had the latest SO installed for ee-6.2.x.

Below is a screencast:
bug

**Comment by jonmak08** [comment]
Hey @jgok @jonathanmccann @holatuwol,

Do you have any update on how to reproduce this issue?

**Comment by jgok** [comment]
Hi @jonmak08 ,

I looked at this issue with @holatuwol, and it appears that you are not able to reproduce this issue because the Notifications portlet is not showing up (without it, there is no race condition).

Do you know if there is an issue with your Notifications portlet?

**Comment by jgok** [comment]
Hi @jonmak08 ,

I cleared out my portal and rebuilt 62x with SO and I was able to reproduce the issue.

Here are some steps to reproduce consistently (from @holatuwol):

1.   Sign in with both users and start a conversation with a few messages between the two users.
2. Add a conditional breakpoint to PollerServlet.service() which stops for the "test" user. Example code which works is: PortalUtil.getUser(request).getScreenName().equals("test")
3. Wait until the conditional breakpoint is hit.
4. Switch to the browser for the "test" user and click on a link.
5. Allow the breakpoint to proceed and it should hit the conditional breakpoint again.
6. Allow this second request to proceed.

Expected behavior is that the chat portlet will show a message. Actual behavior is that the chat portlet message will show up blank.

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/natecavanaugh/liferay-portal/pull/3289

View just my changes: https://github.com/jonmak08/liferay-portal/compare/jonathanmccann:ae04992abd...0b70952188
View total diff: https://github.com/jonmak08/liferay-portal/compare/435f312ee3...0b70952188

**Pull request closed without merging**
