### PR TITLE
[Technical-Support] LPS-56585 Input Date taglib should use localized validation

### PR DESCRIPTION
**Pull request by zsagia**
Hey Jon,

I'm sending you this pull because I saw that you did review on LPS-55223 which caused a regression.

My issue is that if you change user's language to 'en_GB' then the validation in input_date taglib will be failed when you change a date value or submit form. This behavior was caused by LPS-55223 which added an <aui:validator type="date"> to date input.

I think this wan't tested with 'en_GB' language. :)

If this change is good and we need it then we mustn't use form-validate default date validation method because it tries to instantiate a new Date with the given text.

I think in this case the correct date validation would be if we use a mask or pattern for Date creation.

Please review my fix but I know that to use global document object is not the best solution but I don't have better idea. Change it if you can.

Thanks in advance,
 Zsaga

### CODE REVIEW

**Comment by jonmak08** [comment]
Hey @zsagia,

I think we should make this change in ```aui-form-validator``` so it can capture all use cases for this issue rather than just in the taglib.

Inside of ```aui-form-validator.js```, when we check the validity of the date (https://github.com/liferay/alloy-ui/blob/master/src/aui-form-validator/js/aui-form-validator.js#L160...L164) we should be checking the mask/locale that it should test against.

Can you look into making this change and send me a pull request?

I think we might have to update the taglib to have a ```mask``` attribute added to the date, but we  can see if there is any other way to pass the date ```mask``` in.

Please let me know if you have any questions.  Thanks!

**Comment by zsagia** [comment]
Hey @jonmak08,

That kind of solution was my first idea what you mentioned in your response but  because we use one form-validator instance for one form instance thus I can imagine that use case when we want to use more date input with different masks. In this case the given mask strings always override each other and the last will be set in form-validator.

This was the reason that I didn't modified form-validator and put this logic to input_date taglib.

Thanks,
 Zsaga

**Comment by jonmak08** [comment]
Hey @zsagia,

I spoke with @natecavanaugh about this issue and we will proceed with your fix because it will be the easiest to backport.  @natecavanugh stated that if we add an attribute to the ```<aui:validator name="date" />``` it would be an attribute specific to just the ```date``` validator and useless in all other validators.  The validators are meant to be easy and generic ways to test things quickly.  If users want to test custom date formats, they will have to implement a custom validator like we are implementing in the taglib changes you have added here.

We will also need to make these changes in AUI as I stated where we can pass a mask to the form validator if needed.

Please let me know if you have any questions.  Thanks!

**Comment by jonmak08** [comment]
Sent for review.  Thanks!

New Pull Request: https://github.com/natecavanaugh/liferay-portal/pull/3316

**Pull request closed without merging**
