### PR TITLE
[TECHNICAL-SUPPORT] LPS-66825

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @fortunatomaldonado

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonathanmccann** [comment]
ci:reopen

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonmak08** [comment]
Reviewed. Thanks!
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/55428
View total diff: https://github.com/jonmak08/liferay-portal/compare/7da3c35236...ca9911d76d

**Pull request closed without merging**
