### PR TITLE
LPS-65343 - remove random senna 'zx' param from query string in filters, so that css resources can be cached on the server

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Jon,

Attached is another update for https://issues.liferay.com/browse/LPS-65343.

This is in addition to this commit: 2e5fd81ddaa5bbeedce815bd2fe1cd2e276e9c76.

The addition of the 'zx' random param by senna was causing every css request to be minified again instead of using the cached version.  These changes remove that param when checking for it in the cache.

I'm not a huge fan of the fact that with these changes there is now the string "zx" hard coded in three places, but I don't see a good place to create a constant for this.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by michaelhashimoto** [comment]
ci:stop

**Comment by michaelhashimoto** [comment]
I broke this build and am restarting it.

Sorry for the inconveniences.

ci:restart

**Comment by mjbradford89** [comment]
ci:retest

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/brunobasto/liferay-portal/pull/576
View total diff: https://github.com/jonmak08/liferay-portal/compare/5debfdb5e0...95a326bf9c

**Pull request closed without merging**
