### PR TITLE
LPS-59133

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jonmak08,

Attached is an update for http://issues.liferay.com/browse/LPS-59133.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:retest

**Comment by jpince** [comment]
@jonmak08 the SF error from `JavaSourceProcessorTest.testIncorrectIfStatement` is not unique to your pull, I'm trying to find the cause of this failure.

The `SourceFormatterTest.testSourceFormatter` error `missing language key: share-this-application-on-any-website` belongs to you :-P

**Comment by jonmak08** [comment]
Weird, I added that commit for the missing language key but its gone missing...hmmm.  I'll add it back and retest again!

**Comment by jonmak08** [comment]
ci:retest

**Comment by jonmak08** [comment]
ci:retest

**Comment by jonmak08** [comment]
Hey @jpince,

I assume these new errors are a non issue?  Can you confirm?

**Comment by jpince** [comment]
@jonmak08 I wouldn't worry about the other ones, but the SF error is still present (click on the [/modules-unit-jdk8 batch](https://test-1-1.liferay.com/job/test-portal-acceptance-pullrequest-batch(master)/31409/AXIS_VARIABLE=0,label_exp=!master/testReport/junit/com.liferay.source.formatter/SourceFormatterTest/testSourceFormatter/))
```
java.lang.Exception: missing language key: share-this-application-on-any-website: ../../../modules/apps/web-experience/portlet-configuration/portlet-configuration-web/src/main/resources/META-INF/resources/edit_sharing.jsp
```
:(

**Comment by jonmak08** [comment]
ci:retest

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal/pull/42696

**Pull request closed without merging**
