### PR TITLE
LPS-85557 IE11 focus after modal

### PR DESCRIPTION
**Pull request by SpencerWoo**
https://issues.liferay.com/browse/LPS-85557

Modified from https://github.com/blzaugg/liferay-portal/pull/189 with Byran's changes.

### CODE REVIEW

**Comment by blzaugg** [comment]
@jonmak08, LGTM. If you don't get to this before I finish LPP-31653 (1-2 days), I take this from you.

**Comment by SpencerWoo** [comment]
Hey all, any update on this one?

**Comment by jonmak08** [comment]
Hey @SpencerWoo,

I am reviewing this today.  Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
Reviewed. Thanks!
Pull request submitted at: https://github.com/brianchandotcom/liferay-portal/pull/64413

View just my changes: https://github.com/jonmak08/liferay-portal/compare/SpencerWoo:278a6eb93d...d277a6b852
View total diff: https://github.com/jonmak08/liferay-portal/compare/29cff0d243...d277a6b852

**Pull request closed without merging**
