### PR TITLE
LPS-127457

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jonmak08,

Attached is an update for http://issues.liferay.com/browse/LPS-127457.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:forward

**Comment by georgel-pop-lr** [comment]
> Hey @jonmak08,
> 
> Attached is an update for http://issues.liferay.com/browse/LPS-127457.
> 
> Please let me know if you have any questions. Thanks!

Hi @jonmak08,

thanks for your review, no question atm I will bring this to 7.1.x branch.

Regards.

**Pull request closed without merging**
