### PR TITLE
[TECHNICAL-SUPPORT] LPS-69041

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @NolanChan

### CODE REVIEW

**Comment by jonmak08** [comment]
Hey @jonathanmccann and @NolanChan,

I just started my ee-7.0.x/portal and was unable to reproduce this issue.  I was on Git SHA ID: dee4e0e77c2dccc48b9c5c1a3da7441ad1d843e7.

Can you please confirm this is still an issue on ee-7.0.x?  If it is not, we might just be missing a backport that is needed for 7.0.x.

Please let me know if you have any questions. Thanks!

**Comment by jonmak08** [comment]
This is what I see in ee-7.0.x on IE11:

image

**Comment by NolanChan** [comment]
Hmm, maybe my IE 11 is a bit outdated (although I grabbed my VM from Microsoft) but here's what I'm seeing:

longselectbox

**Comment by jonmak08** [comment]
I don't love this fix and something seems wrong about it.  If we did this and it only affects, IE11, can we update this so the changes only affect IE11?

Can you guys please review and see if there is a better way to resolve this issue?

**Pull request closed without merging**
