### PR TITLE
[Technical Support] LPS-67718

### PR DESCRIPTION
**Pull request by dustinryerson**
Hey @jonmak08,

This is an update for https://issues.liferay.com/browse/LPS-67718. I've tested for the issue you reported here: https://github.com/jonmak08/liferay-portal/pull/1611#issuecomment-243901278. It seems to be resolved by these changes.

Please let me know if you have any questions.

Thanks!

### CODE REVIEW

**Comment by daledotshan** [comment]
Hey jonmak,
Could you help to review this pull request as high priority since one ee customer is waiting for this fix?

Thanks

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/jbalsas/liferay-portal/pull/594
View total diff: https://github.com/jonmak08/liferay-portal/compare/5087ea1b90...a741fa4b63

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/brianchandotcom/liferay-portal/pull/43121

**Comment by jonmak08** [comment]
New Pull Request: https://github.com/juliocamarero/liferay-portal/pull/4263

**Pull request closed without merging**
