### PR TITLE
LPS-56395 Have the code button hovered when adding code

### PR DESCRIPTION
**Pull request by zxdgoal**
Hey Jon

The original bbcode plugin did not have refresh method.

We have to construct one if we want the code button behaves the same with the others from ckeditor plugins.

Let me know if you have any concerns.

Thanks
John

### CODE REVIEW

**Comment by zxdgoal** [comment]
Hey @jonmak08 

You are right. The context itself seems enough to make it work.

I updated this pr.

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/natecavanaugh/liferay-portal/pull/3308

View just my changes: https://github.com/jonmak08/liferay-portal/compare/zxdgoal:6ce963ee29...29a2f6c140
View total diff: https://github.com/jonmak08/liferay-portal/compare/78a873c6a4...29a2f6c140

**Comment by zxdgoal** [comment]
It seems that I included the ckeditor.zip by mistake.

Sorry for that.

I didn't notice that.

**Comment by jonmak08** [comment]
Hey @zxdgoal,

Not a problem!  That is why we have peer reviews =)   Thanks for sending all these fixes over!

**Pull request closed without merging**
