### PR TITLE
LPS-60911 - Migrate ui:social-activities taglib to social-taglib module

### PR DESCRIPTION
**Pull request by mjbradford89**
Hey Jon,

Attached is an update for https://issues.liferay.com/browse/LPS-60911.

I talked to @sergiogonzalez and he'd like us to send this to him for review once it's ready.

Please let me know if there are any issues.

Thanks!

### CODE REVIEW

**Comment by mjbradford89** [comment]
Hey @jonmak08,  I'm working on the rest of the social-taglibs migration on top of these changes.  And I was thinking it would probably be best to rename all of the taglibs from `liferay-social:social-activities` to `liferay-social:activities`, `liferay-social:social-bookmarks` to `liferay-social:bookmarks`, etc.

I could add a commit to this pull renaming this one if you think it's a good idea.

**Comment by jonmak08** [comment]
Hey @mjbradford89,

I think that would be a good idea to rename these taglibs like you mention.  I am currently reviewing this  taglib and can send it back to you when I am done to rename it.

**Comment by mjbradford89** [comment]
Cool, I can definitely do the rename. Thanks!

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!

**Pull request closed without merging**
