### PR TITLE
LPS-121938

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jonmak08,

Attached is an update for http://issues.liferay.com/browse/LPS-121938.

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:stop

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by julien** [comment]
ci:stop

**Comment by julien** [comment]
@jonmak08 I cherry-picked [7e33e6d](7e33e6d5cd57f842fac576685694c2a7acb2641d) and re-invoked the tests [here]https://github.com/liferay-frontend/liferay-portal/pull/911)

**Comment by julien** [comment]
ci:close

**Comment by jonmak08** [comment]
Thanks @julien!

**Pull request closed without merging**
