### PR TITLE
LPS-66589

### PR DESCRIPTION
**Pull request by blzaugg**

### CODE REVIEW

**Comment by jonmak08** [comment]
Merged and pushed.  Thanks!
Pull request submitted at: https://github.com/natecavanaugh/liferay-portal/pull/4029
View total diff: https://github.com/jonmak08/liferay-portal/compare/d2b1888481...ad1a96bdfd

**Comment by jonmak08** [comment]
Hey @blzaugg,

I still was not able to get this to load without errors.  Can you check again and see if you can get it to work successfully?  If it does, please send it to @natecavanaugh for review.

Please let me know if you have any questions. Thanks!

**Comment by blzaugg** [comment]
I could not get the startup/load errors.

https://github.com/natecavanaugh/liferay-portal/pull/4033

**Pull request closed without merging**
