### PR TITLE
LPS-121926

### PR DESCRIPTION
**Pull request by jonmak08**
Hey @jonmak08,

Attached is an update for http://issues.liferay.com/browse/LPS-121926.

**Test Plan:**
1. Build Liferay Portal w/ DXP Modules
2. Login to Liferay
3. Click the **Control Menu**
4. Go to **Configuration** -> **Reports Admin**
portal-reports-engine-console

Please let me know if you have any questions. Thanks!

### CODE REVIEW

**Comment by jonmak08** [comment]
ci:test:sf

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:test:relevant

**Comment by jonmak08** [comment]
ci:test:relevant

**Review by ambrinchaudhary — APPROVED** [review]

**Comment by jonmak08** [comment]
ci:forward

**Pull request closed without merging**
