### PR TITLE
[TECHNICAL-SUPPORT] LPS-78847

### PR DESCRIPTION
**Pull request by jonathanmccann**
/cc @gregory-bretall

### CODE REVIEW

**Comment by jonathanmccann** [comment]
ci:test

**Comment by jonmak08** [comment]
Hey @jonathanmccann and @gregory-bretall,

I was unable to reproduce the error stated in the JIRA ticket.  You can see my screencast of the steps I followed to try to reproduce this issue.

bug

It looks like QA was also unable to reproduce the issue (https://issues.liferay.com/browse/LPS-78847?focusedCommentId=1266672&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-1266672).

Please advise.  Thanks!

**Comment by jonathanmccann** [comment]
@jonmak08 In the past when the code is the same between 7.0.x and Master, the ER team wants the fix committed to Master first, even if it's not reproducible in the same way. We could go through the hassle of making a custom portlet to reproduce it, but thought it would be simpler to get it committed since we can show that it is broken on 7.0.x. @gregory-bretall feel free to add more context if I'm missing anything.

**Comment by gregory-bretall** [comment]
Hi @jonmak08 what browser were you testing on? In my testing I was never able to reproduce this issue on Google Chrome for some reason, only on Firefox, MS Edge, and IE11. If you have not tried using one of those browsers to reproduce, please try it and let me know if it works in that case. If you have any other questions in regards to reproducing the issue just let me know.

**Comment by jonmak08** [comment]
Reviewed. Thanks!
View total diff: https://github.com/jonmak08/liferay-portal/compare/79065bdf9f...bf1b388be3

**Pull request closed without merging**
